title: Welcome 
author: Archana Kalburgi
#email: 
description: > # this means to ignore newlines until "baseurl:"
  My learnings 
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  archanakalburgi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
