title: Archana Kalburgi
author: Archana Kalburgi

description: > # this means to ignore newlines until "baseurl:"

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

github_username: archanakalburgi # DO NOT include the @ character, or else the build will fail!
linkedin_username: archana-kalburgi

background_image: /images/bg.jpg

show_excerpts: false # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
